auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0

common:
  instance_addr: loki
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
#ingester:
#  lifecycler:
#    address: loki  # 도커 컴포즈 파일에서 정의한 서비스 이름으로 수정
#    ring:
#      kvstore:
#        store: inmemory
#      replication_factor: 1
#    final_sleep: 0s
#  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
#  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
#  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
#  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
#  max_transfer_retries: 0     # Chunk transfers disabled

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2024-05-17
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf
